"""
Django settings for roma project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-q5qhkg3q2jlgygcn@3w6xmq#8=txu9jo=jw3zx--$x9+!__!n#"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "yes", "on")

ADD_ALLOWED_HOST = os.environ.get("ALLOWED_HOST", "*")

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "0.0.0.0",
    ADD_ALLOWED_HOST,
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "user",
    "data",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "roma.middleware.arangodb_middleware.ArangoDBMiddleware",
]

ARANGO_DB_NAME = os.getenv("ARANGO_DB_NAME", "rms")
# ARANGO_DB_NAME = "rms_test" if DEBUG else ARANGO_DB_NAME
ARANGO_USERNAME = os.getenv("ARANGO_USERNAME", "root")
ARANGO_PASSWORD = os.getenv("ARANGO_PASSWORD", "blabla")
ARANGO_HOST = os.getenv("ARANGO_HOST", "http://localhost:8529")


ADD_ALLOWED_ORIGINS = os.environ.get("CORS_ALLOWED_ORIGINS")

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200",
    "http://127.0.0.1:8080",
    "http://localhost:8080",
    "http://127.0.0.1:8010",
    "http://127.0.0.1:8020",
    "http://localhost:8010",
    "http://localhost:8020",
    ADD_ALLOWED_ORIGINS,
]

ADD_ALLOWED_ORIGINS = os.environ.get("CORS_ALLOWED_ORIGINS")
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200",
    "http://127.0.0.1:8080",
    "http://localhost:8080",
    "http://127.0.0.1:8010",
    "http://127.0.0.1:8020",
    "http://localhost:8010",
    "http://localhost:8020",
]

if ADD_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.extend(ADD_ALLOWED_ORIGINS.split(","))

CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        #        'rest_framework.permissions.IsAuthenticated',
    ],
}


ROOT_URLCONF = "roma.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "roma.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "data": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("MYSQL_DATA_NAME", "romani"),
        "USER": os.getenv("MYSQL_DATA_USER", "root"),
        "PASSWORD": os.getenv("MYSQL_DATA_PASSWORD", ""),
        "HOST": os.getenv("MYSQL_DATA_HOST", "localhost"),
        "PORT": os.getenv("MYSQL_DATA_PORT", "3306"),
    },
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("MYSQL_DEFAULT_NAME", "rms"),
        "USER": os.getenv("MYSQL_DEFAULT_USER", "root"),
        "PASSWORD": os.getenv("MYSQL_DEFAULT_PASSWORD", ""),
        "HOST": os.getenv("MYSQL_DEFAULT_HOST", "localhost"),
        "PORT": os.getenv("MYSQL_DEFAULT_PORT", "3306"),
    },
}
DATABASE_ROUTERS = [
    "roma.dbrouters.DBRouter",
]

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# Localisation
LANGUAGE_CODE = "en"
TIME_ZONE = "CET"
USE_I18N = True
USE_L10N = True
USE_TZ = True

LOCALE_PATHS = (os.path.join(BASE_DIR, "locale"),)

LANGUAGES = (
    ("en", "English"),
    ("de", "Deutsch"),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# URL configuration
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles/")
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
MEDIA_URL = "/media/"
LOGIN_URL = "/login"
LOGIN_REDIRECT_URL = "/"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
